config/routes.rb
Rails.application.routes.draw do
  # Authentication
  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions"}

  # Root path
  devise_scope :user do
    authenticated :user do
      root to: redirect("dashboard")
    end

    unauthenticated :user do
      root "static_pages#splash", as: :unauthenticated_root
    end
  end

  get "about", to: "static_pages#about"

  get "dashboard", to: "users#show", as: :dashboard

  resources :journals, only: %i[new create index edit update destroy] do
    resources :notes, shallow: true do
      resources :comments, shallow: true
      resources :counters, shallow: true do
        member do
          patch "increment"
          patch "decrement"
        end
      end
    end
  end

  resources :campaigns do
    resources :invitations, only: %i[new create index],
      controller: "campaigns/invitations"
    resources :membership_journals, only: %i[new create]
  end

  resources :membership_journals, only: %i[destroy]

  resources :invitations, only: %i[destroy]

  namespace :users do
    resources :invitations, only: %i[index show] do
      post :accept, on: :member
    end
  end

  resources :memberships, only: %i[destroy]

  resources :notifications, only: %i[index destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :note
  belongs_to :author, class_name: "User"

  scope :desc, -> { order(created_at: :desc) }

  validates :body, length: {minimum: 2}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_note, only: %i[index new create]
  before_action :set_comment, only: %i[edit update destroy show]

  def index
    @comments = @note.comments.desc
  end

  def new
    @comment = @note.comments.build
  end

  def create
    @comment = @note.comments.build(comment_params.merge(author: current_user))

    respond_to do |format|
      if @comment.save
        format.turbo_stream do
          @comment.broadcast_prepend_to(
            [@note, :comments],
            target: helpers.dom_id(@note, :comments)
          )

          @comment = @note.comments.build
        end
        format.html { redirect_to @note }
      else
        format.turbo_stream {}
        format.html do
          flash.now[:error] = @comment.errors.full_messages
          redirect_to @note, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @comment.destroy

    respond_to do |format|
      format.turbo_stream { @comment.broadcast_remove }
      format.html do
        flash[:success] = "Comment successfully deleted."
        redirect_to note_comments_path(@comment.note)
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.turbo_stream { @comment.broadcast_replace }
        format.html { redirect_to @comment }
      else
        format.turbo_stream { @comment.broadcast_replace }
        format.html do
          flash.now[:error] = @comment.errors.full_messages
          redirect_to @note, status: :unprocessable_entity
        end
      end
    end
  end

  def show
  end

  private

  def set_note
    @note = Note.find(params[:note_id])

    authorize! context: {note: @note}
  end

  def set_comment
    @comment = Comment.find(params[:id])

    authorize! @comment
  end

  def comment_params
    params.require(:comment).permit(:body, :author_id, :note_id)
  end
end

app/views/comments/_comment.html.erb
<%= turbo_stream_from comment %>
<%= turbo_frame_tag comment do %>
  <div>
    <%= comment.author.username %>
  </div>
  <p>
    <%= comment.body %>
  </p>
  <ul class="flex justify-end">
    <%= link_to edit_comment_path(comment), 
      data: {testid: "#{dom_id(comment)}-edit-link"},
      aria: {label: "edit comment"} do
    %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
      </svg>
    <% end %>
    <%= button_to comment_path(comment), method: :delete,
      data: {
        turbo_confirm: "This will permanently delete this comment. Are you sure?",
        testid: "#{dom_id(comment)}-destroy-btn"
      },
      aria: {label: "delete comment"} do
    %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15.362 5.214A8.252 8.252 0 0112 21 8.25 8.25 0 016.038 7.048 8.287 8.287 0 009 9.6a8.983 8.983 0 013.361-6.867 8.21 8.21 0 003 2.48z" />
        <path stroke-linecap="round" stroke-linejoin="round" d="M12 18a3.75 3.75 0 00.495-7.467 5.99 5.99 0 00-1.925 3.546 5.974 5.974 0 01-2.133-1A3.75 3.75 0 0012 18z" />
      </svg>
    <% end %>
  </ul>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [note, comment],
  class: "flex flex-col space-y-[8px]" do |form|
%>
  <% if comment.errors.any? %>
    <ul
      class="flex flex-col space-y-[4px]"
    >
      <% comment.errors.full_messages.each do |message| %>
        <li
          class="font-medium text-rose-400 bg-slate-700 px-4 py-2 rounded-md"
        >
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <%= form.label :body, "Comment",
    class: "block text-sm text-indigo-400 font-bold"
  %>
  <%= form.text_area :body,
    class: "w-full bg-slate-800 border-slate-600 rounded-md placeholder:italic placeholder:text-slate-600",
    data: {testid: "#{dom_id(comment)}-body-input"}
  %>
  <%= form.submit "Save Comment",
    class: "h-8 w-full px-[8px] text-lg text-stone-300 bg-indigo-500 rounded-md hover:bg-indigo-600 focus:bg-indigo-700 hover:cursor-pointer",
    data: {testid: "#{dom_id(comment)}-save-btn"}
  %>
  <% if comment.persisted? %>
    <%= link_to "Cancel", comment,
      class: "h-8 w-full px-[8px] leading-8 text-center align-middle text-lg text-stone-300 bg-rose-400 rounded-md hover:bg-rose-500 focus:bg-rose-600 hover:cursor-pointer"
    %>
  <% end %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%# Prepend is performed by Turbo Stream channel in controller %>

<%= turbo_stream.replace dom_id(@note, :new_comment) do %>
  <%= turbo_frame_tag dom_id(@note, :new_comment) do %>
    <%= render "form", {note: @note, comment: @comment} %>
  <% end %>
<% end %>

app/views/comments/edit.html.erb
<%= link_to "Back to #{@comment.note.name}", note_path(@comment.note) %>

<%= turbo_frame_tag @comment do %>
  <%= render "form", {note: nil, comment: @comment} %>
<% end %>

app/views/comments/index.html.erb
<%= link_to "Back to #{@note.name}", note_path(@note) %>

<%= turbo_frame_tag dom_id(@note, :comments) do %>
  <%= render @comments %>
<% end %>

app/views/comments/new.html.erb
<%= link_to "Back to #{@note.name}", note_path(@note) %>

<%= turbo_frame_tag dom_id(@note, :new_comment) do %>
  <%= render "form", {note: @note, comment: @comment} %>
<% end %>

app/views/comments/show.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render @comment %>
<% end %>