config/routes.rb
Rails.application.routes.draw do
  # Authentication
  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions"}

  # Root path
  devise_scope :user do
    authenticated :user do
      root to: redirect("dashboard")
    end

    unauthenticated :user do
      root "static_pages#splash", as: :unauthenticated_root
    end
  end

  get "about", to: "static_pages#about"

  get "dashboard", to: "users#show", as: :dashboard

  resources :journals, only: %i[new create index edit update destroy] do
    resources :notes, shallow: true do
      resources :comments, shallow: true
      resources :counters, shallow: true do
        member do
          patch "increment"
          patch "decrement"
        end
      end
    end
  end

  resources :campaigns do
    resources :invitations, only: %i[new create index],
      controller: "campaigns/invitations"
    resources :membership_journals, only: %i[new create]
  end

  resources :membership_journals, only: %i[destroy]

  resources :invitations, only: %i[destroy]

  namespace :users do
    resources :invitations, only: %i[index show] do
      post :accept, on: :member
    end
  end

  resources :memberships, only: %i[destroy]

  resources :notifications, only: %i[index destroy]
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :author, class_name: "User"

  has_many :notes, dependent: :destroy
  has_many :membership_journals
  has_many :memberships, through: :membership_journals
  has_many :campaigns, through: :memberships

  validates :name, presence: true
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: %i[edit update destroy]
  before_action :authorize!, only: %i[new index]

  def new
    @journal = Journal.new
  end

  def create
    @journal = Journal.new(journal_params.merge(author: current_user))
    authorize! @journal

    if @journal.save
      redirect_to journal_notes_path(@journal)
    else
      flash.now[:error] = @journal.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @journals = current_user.journals
  end

  def edit
  end

  def update
    if @journal.update(journal_params)
      redirect_to journal_notes_path(@journal)
    else
      flash.now[:error] = @journal.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @journal.destroy

    flash[:success] = "#{@journal.name} Journal successfully deleted."
    redirect_to journals_path
  end

  private

  def set_journal
    @journal = Journal.find(params[:id])

    authorize! @journal
  end

  def journal_params
    params.require(:journal).permit(:name, :author_id)
  end
end

app/views/journals/_form.html.erb
<%= form_with model: journal,
  class: "flex flex-col items-stretch mb-[16px]" do |form|
%>
  <div
    class="space-y-[16px]"
  >
    <div> 
      <%= form.label :name, "Journal Name",
        class: "block text-sm text-indigo-400 font-bold"
      %>
      <%= form.text_field :name,
        class: "w-full bg-slate-800 border-slate-600 rounded-md placeholder:italic placeholder:text-slate-600",
        placeholder: "Name your journal",
        data: {testid: "journal-name-input"}
      %>
    </div>
    <%= form.submit "Save Journal",
      class: "h-8 w-full px-[8px] text-lg text-stone-300 bg-indigo-500 rounded-md hover:bg-indigo-600 focus:bg-indigo-700 hover:cursor-pointer",
      data: {testid: "journal-save-btn"}
    %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1
  class="text-xl text-lime-300 font-bold mb-[8px]"
>
  Edit Journal
</h1>

<%= render partial: "form", locals: {journal: @journal} %>
<%= button_to "Delete", journal_path(@journal), method: :delete,
  class: "h-8 w-full px-[8px] text-lg text-stone-300 bg-rose-400 rounded-md hover:bg-rose-500 focus:bg-rose-600 hover:cursor-pointer",
  data: {
    turbo_confirm: "Are you sure? All notes in the journal will be lost!",
    testid: "journal-delete-btn"
  }
%>

app/views/journals/index.html.erb
<h2
  class="text-lg text-lime-300 font-bold mb-[16px]"
>
  <%= current_user.username %>'s Journals
</h2>
<%= link_to "New journal", new_journal_path,
  class: "",
  data: { testid: "new-journal-link" }
%>
<ul data-testid="journals-list">
  <% @journals.each do |journal| %>
    <li>
      <h3><%= link_to journal.name, journal_notes_path(journal) %></h3>
      <div>
        <%= link_to "Edit", edit_journal_path(journal) %>
        <%= button_to "Delete", journal_path(journal), method: :delete,
          data: {
            turbo_confirm: "Are you sure? All notes in the journal will be lost!",
            testid: "journal-delete-btn"
          }
        %>
      </div>
    </li>
  <% end %>
</ul>

app/views/journals/new.html.erb
<h2
  class="text-xl text-lime-300 font-bold mb-[16px]"
>
  New Journal
</h2>
<%= render partial: "form", locals: {journal: @journal} %>