config/routes.rb
Rails.application.routes.draw do
  # Authentication
  devise_for :users, controllers: {registrations: "users/registrations",
                                   sessions: "users/sessions"}

  # Root path
  devise_scope :user do
    authenticated :user do
      root to: redirect("dashboard")
    end

    unauthenticated :user do
      root "static_pages#splash", as: :unauthenticated_root
    end
  end

  get "about", to: "static_pages#about"

  get "dashboard", to: "users#show", as: :dashboard

  resources :journals, only: %i[new create index edit update destroy] do
    resources :notes, shallow: true do
      resources :comments, shallow: true
      resources :counters, shallow: true do
        member do
          patch "increment"
          patch "decrement"
        end
      end
    end
  end

  resources :campaigns do
    resources :invitations, only: %i[new create index],
      controller: "campaigns/invitations"
    resources :membership_journals, only: %i[new create]
  end

  resources :membership_journals, only: %i[destroy]

  resources :invitations, only: %i[destroy]

  namespace :users do
    resources :invitations, only: %i[index show] do
      post :accept, on: :member
    end
  end

  resources :memberships, only: %i[destroy]

  resources :notifications, only: %i[index destroy]
end

app/models/counter.rb
class Counter < ApplicationRecord
  belongs_to :note

  scope :persisted, -> { where.not(id: nil) }
end

app/controllers/counters_controller.rb
class CountersController < ApplicationController
  skip_verify_authorized

  before_action :set_note, only: %i[index new create]
  before_action :set_counter,
    only: %i[edit update destroy show increment decrement]

  def index
    @counters = @note.counters.order(created_at: :desc)
  end

  def new
    @counter = @note.counters.build
  end

  def create
    @counter = @note.counters.build(counter_params)

    respond_to do |format|
      if @counter.save
        format.turbo_stream do
          @counter.broadcast_prepend_to(
            [@note, :counters],
            target: helpers.dom_id(@note, :counters)
          )

          @counter = @note.counters.build
        end
        format.html { redirect_to @note }
      else
        format.turbo_stream {}
        format.html do
          flash.now[:error] = @counter.errors.full_messages
          redirect_to @note, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @counter.destroy

    respond_to do |format|
      format.turbo_stream { @counter.broadcast_remove }
      format.html do
        flash[:success] = "counter successfully deleted."
        redirect_to note_counters_path(@counter.note)
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @counter.update(counter_params)
        format.turbo_stream { @counter.broadcast_replace }
        format.html { redirect_to @counter }
      else
        format.turbo_stream { @counter.broadcast_replace }
        format.html do
          flash.now[:error] = @counter.errors.full_messages
          redirect_to @note, status: :unprocessable_entity
        end
      end
    end
  end

  def increment
    respond_to do |format|
      if @counter.increment!(:count)
        format.turbo_stream { @counter.broadcast_replace }
        format.html { redirect_to @counter }
      else
        format.turbo_stream { @counter.broadcast_replace }
        format.html do
          flash.now[:error] = @counter.errors.full_messages
          redirect_to @note, status: :unprocessable_entity
        end
      end
    end
  end

  def decrement
    respond_to do |format|
      if @counter.decrement!(:count)
        format.turbo_stream { @counter.broadcast_replace }
        format.html { redirect_to @counter }
      else
        format.turbo_stream { @counter.broadcast_replace }
        format.html do
          flash.now[:error] = @counter.errors.full_messages
          redirect_to @note, status: :unprocessable_entity
        end
      end
    end
  end

  private

  def set_note
    @note = Note.find(params[:note_id])

    # authorize! context: {note: @note}
  end

  def set_counter
    @counter = Counter.find(params[:id])

    # authorize! @counter
  end

  def counter_params
    params.require(:counter).permit(:label, :count)
  end
end

app/views/counters/_counter.html.erb
<%= turbo_stream_from counter %>
<%= turbo_frame_tag counter do %>
  <div
    class="flex space-x-2"
  >
    <ul
      class="flex space-x-1"
    >
      <li><%= counter.label %>:</li>
      <li><%= counter.count %></li>
    </ul>
    <ul class="flex space-x-2 justify-end">
      <li>
        <%= button_to increment_counter_path(counter), method: :patch,
          data: {
            testid: "#{dom_id(counter)}-increment-btn"
          },
          aria: {label: "increment counter"} do
        %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
          </svg>
        <% end %>
      </li>
      <li>
        <%= button_to decrement_counter_path(counter), method: :patch,
          data: {
            testid: "#{dom_id(counter)}-decrement-btn"
          },
          aria: {label: "decrement counter"} do
        %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M5 12h14" />
          </svg>
        <% end %>
      </li>
      <li>
        <%= link_to edit_counter_path(counter), 
          data: {testid: "#{dom_id(counter)}-edit-link"},
          aria: {label: "edit counter"} do
        %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
          </svg>
        <% end %>
      </li>
      <li>
        <%= button_to counter_path(counter), method: :delete,
          data: {
            turbo_confirm: "This will permanently delete this counter. Are you sure?",
            testid: "#{dom_id(counter)}-destroy-btn"
          },
          aria: {label: "delete counter"} do
        %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.362 5.214A8.252 8.252 0 0112 21 8.25 8.25 0 016.038 7.048 8.287 8.287 0 009 9.6a8.983 8.983 0 013.361-6.867 8.21 8.21 0 003 2.48z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 18a3.75 3.75 0 00.495-7.467 5.99 5.99 0 00-1.925 3.546 5.974 5.974 0 01-2.133-1A3.75 3.75 0 0012 18z" />
          </svg>
        <% end %>
      </li>
    </ul>
  </div>
<% end %>

app/views/counters/_form.html.erb
<%= form_with model: [note, counter],
  class: "flex space-x-[8px] items-center",
  data: {testid: "counter-form"} do |form|
%>
  <% if counter.errors.any? %>
    <ul
      class="flex flex-col space-y-[4px]"
    >
      <% counter.errors.full_messages.each do |message| %>
        <li
          class="font-medium text-rose-400 bg-slate-700 px-4 py-2 rounded-md"
        >
          <%= message %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <%= form.label :label, "Counter",
    class: "block text-sm text-indigo-400 font-bold"
  %>
  <%= form.text_field :label,
    class: "h-8 w-full bg-slate-800 border-slate-600 rounded-md placeholder:italic placeholder:text-slate-600",
    data: {testid: "#{dom_id(counter)}-label-input"}
  %>
  <%= form.submit "Save counter",
    class: "h-8 w-full px-[8px] text-lg text-stone-300 bg-indigo-500 rounded-md hover:bg-indigo-600 focus:bg-indigo-700 hover:cursor-pointer",
    data: {testid: "#{dom_id(counter)}-save-btn"}
  %>
  <% if counter.persisted? %>
    <%= link_to "Cancel", counter,
      class: "h-8 w-full px-[8px] leading-8 text-center align-middle text-lg text-stone-300 bg-rose-400 rounded-md hover:bg-rose-500 focus:bg-rose-600 hover:cursor-pointer"
    %>
  <% end %>
<% end %>

app/views/counters/create.turbo_stream.erb
<%# Prepend is performed by Turbo Stream channel in controller %>

<%= turbo_stream.replace dom_id(@note, :new_counter) do %>
  <%= turbo_frame_tag dom_id(@note, :new_counter) do %>
    <%= render "form", {note: @note, counter: @counter} %>
  <% end %>
<% end %>

app/views/counters/edit.html.erb
<%= link_to "Back to #{@counter.note.name}", note_path(@counter.note) %>

<%= turbo_frame_tag @counter do %>
  <%= render "form", {note: nil, counter: @counter} %>
<% end %>

app/views/counters/index.html.erb
<%= link_to "Back to #{@note.name}", note_path(@note) %>

<%= turbo_frame_tag dom_id(@note, :counters) do %>
  <%= render @counters %>
<% end %>

app/views/counters/new.html.erb
<%= link_to "Back to #{@note.name}", note_path(@note) %>

<%= turbo_frame_tag dom_id(@note, :new_counter) do %>
  <%= render "form", {note: @note, counter: @counter} %>
<% end %>

app/views/counters/show.html.erb
<%= turbo_frame_tag @counter do %>
  <%= render @counter %>
<% end %>